SelfServeApp/self-server-rest-client:
  - source: dist/openapi.yml
    dest: Sources/openapi.yml
SelfServeApp/self-server:
  - source: dist/openapi.yml
    dest: Sources/OpenAPIServerStubs/openapi.yml
