openapi: 3.1.0
info:
  title: Self-Server REST API
  description: Self-Server's REST/HTTP API.
  version: 0.1.2
  license:
    name: Internal
    url: https://valdman.works
servers:
  - url: http://{ip_address}:{port}
    description: Local testing IP address and port number.
    variables:
      ip_address:
        default: 127.0.0.1
        description: Server IP address.
      port:
        default: '8080'
        description: Server port number.
tags:
  - name: server
    description: Endpoints for interacting and managing the server itself.
  - name: library
    description: Endpoints for interacting with photo libraries (each library refers to a single device's library).
security:
  - active_session_token: []
paths:
  /servers:
    $ref: paths/servers.yml
  /libraries:
    $ref: paths/libraries.yml
  /libraries/{libraryID}:
    $ref: paths/libraries_{libraryID}.yml
  /libraries/{libraryID}/transfer/stream-test:
    $ref: paths/libraries_{libraryID}_transfer_stream-test.yml
components:
  securitySchemes:
    server_control:
      type: http
      scheme: basic
      description: >-
        A username/password combo used to authenticate requests relating to the server itself, rather than pertaining to a library.
    active_session_token:
      type: http
      scheme: bearer
      description: >-
        A token generated at the start of a WebSocket connection with the
        server, and invalidated when the connection ends.
      bearerFormat: JWT
