name: Bundle API
run-name: Bundling OpenAPI Spec
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'openapi/**'
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
jobs:
  bundle_job:
    name: Bundle Job
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '**/.github/workflows/*.yml'
      - run: npx @redocly/cli bundle main -o dist/openapi.yml
      - name: Commit file if there are changes
        run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Updated bundled API spec."
            git push
          else
            echo Nothing new to commit.
          fi
          
