name: Bundle API
run-name: Bundling OpenAPI Spec
on:
  workflow_dispatch:
jobs:
  bundle_job:
    name: Bundle Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '**/.github/workflows/*.yml'
      # - name: Install Dependencies
      #   run: npm ci
      # - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      # - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      # - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      # - name: Install Redocly
      #   run: npm ci
      # - run: redocly bundle openapi/openapi.json --output dist/openapi.json
      - run: npx @redocly/cli bundle main -o dist/openapi.yml
      - name: Commit file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Updated bundled API spec."
          git push
