name: Sync Spec File
on: 
  push:
    tags:
      - '*'
    branches:
      - main
  workflow_dispatch:
jobs:
  sync_job:
    name: Sync Spec Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          CONFIG_PATH: '.github/sync-spec-config.yml'
          PR_BODY: Updated OpenAPI spec.
          BRANCH_PREFIX: spec-sync
